version: '3.9'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    volumes:
      - ./mlruns:/mlruns

  prefect:
    image: prefecthq/prefect:latest
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
    command: prefect server start

  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn deploy.api.main:app --host 0.0.0.0 --port 8000

  dashboard:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run dashboard/app_streamlit.py
